sudo: required
services:
  - docker

before_install:
  - docker build -t najibalkhala/docker-react-app -f Dockerfile.dev .

script:
  - docker run najibalkhala/docker-react-app npm run test -- --coverage